# Generated by Django 5.2.8 on 2026-03-17 13:22

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_add_shard_key_and_sync_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='shard_key',
            field=models.CharField(db_index=True, help_text='Ключ шарда (например, str(project_id)). Используется для маршрутизации запросов.', max_length=64),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='shard_key',
            field=models.CharField(db_index=True, help_text='Ключ шарда (например, str(project_id)). Используется для маршрутизации запросов.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['created_at'], name='apilog_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='apilog',
            index=models.Index(fields=['endpoint', 'status'], name='apilog_endpoint_status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='auditlog_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['project', 'created_at'], name='auditlog_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['project', 'status'], name='cluster_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['shard_key', 'project'], name='cluster_shard_project_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='keyword_search_vector_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['cluster', 'project'], name='keyword_cluster_project_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['shard_key', 'cluster'], name='keyword_shard_cluster_idx'),
        ),
    ]
