# Generated by Django 5.2.12 on 2026-03-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_cluster_shard_key_alter_keyword_shard_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='analyzer.project'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='analyzer.project'),
        ),
    ]
